import java.io.File;
import java.io.IOException;

import qualify.TestCase;

public class Test5 extends MotherTest {

	public Test5() {
		// An exception is thrown here:
		int i = 'bad integer'
	}

	public void run() {
		check(b)
		System.out.println("I'm in the script 3");
	}

}